# https://docs.travis-ci.com/user/getting-started/

language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

# https://blog.travis-ci.com/2017-04-17-precise-EOL
# Also needed for TensorFlow for glibc 2.7.
dist: trusty

# https://github.com/travis-ci/travis-ci/issues/2890
#before_install:
#  - sudo apt-get build-dep python-scipy
#  - sudo apt-get install -qq python-numpy python-scipy python-matplotlib

# command to install dependencies
# quiet (-qq) to keep log smaller
install:
  - pip install -qq --upgrade pip setuptools wheel
  - pip install -qq --only-binary=numpy,scipy numpy
  - pip install -qq -r requirements.txt
  - pip install -qq tensorflow
  - pip install -qq nose
  - echo "[global]" >> ~/.theanorc
  - echo "device = cpu" >> ~/.theanorc
  - echo "floatX = float32" >> ~/.theanorc

env:
  - TEST=Config
  - TEST=Dataset
  - TEST=demos
  - TEST=Device
  - TEST=EngineTask
  - TEST=EngineUtil
  - TEST=GeneratingDataset
  - TEST=hdf_dump
  - TEST=HDFDataset
  - TEST=LearningRateControl
  - TEST=Log
  - TEST=multi_target
  - TEST=MultiBatchBeam
  - TEST=NativeOp
  - TEST=NativeOp_chunk
  - TEST=NativeOp_sparse
  - TEST=NativeOp_subtensor_batched_index
  - TEST=Network
  - TEST=NetworkBaseLayer
  - TEST=NetworkDescription
  - TEST=NetworkLayer
  - TEST=Pretrain
  - TEST=SprintDataset
  - TEST=SprintInterface
  - TEST=TaskSystem
  - TEST=TaskSystem_SharedMem
  - TEST=TFEngine
  - TEST=TFNativeOp
  - TEST=TFNetworkLayer
  - TEST=TFNetworkRecLayer
  - TEST=TFUpdater
  - TEST=TFUtil
  - TEST=TheanoUtil
  - TEST=Util

# command to run tests
script:
  - nosetests tests/test_$TEST.py

# https://docs.travis-ci.com/user/notifications
# no notifications
notifications:
  email: false
